### ISSUE TITLE
popover 组件的 placement 默认值可以改成 top

### ISSUE THREAD

**Issue by mimoning** [DaoCloud/dao-style#600]
**1.操作系统，浏览器，dao-style 版本:**

* 操作系统： osx
* 浏览器：chrome v70
* dao-style: 1.09

**2.问题描述：**
popover 组件的 placement 默认值为 bottom，感觉有点反人类，大多的 popover 应该是默认是在 trigger 上方的

**3.重现方式：**

**4.其他您认为有价值的信息：**

**Comment by olivewind** [comment]
我觉得 ok。

**Comment by olivewind** [comment]
@jamiefang

**Comment by jamiefang** [comment]
我觉得 ok。+10086
