### ISSUE TITLE
dao-panel: prop min-height does not work as expected

### ISSUE THREAD

**Issue by Zhuzhenghao** [DaoCloud/dao-style#617]
**1.操作系统，浏览器，dao-style 版本:**

* 操作系统： 
* 浏览器：
* dao-style:

**2.问题描述：**
组件dao-panel 在使用的min-height的时候，初始化的bodyHeight是this.height - 26, that means , 我panel的size是m, 那么初始的height是200-26, 但是我min-height是400， bodyHeight却是174px,  emmmm

**3.重现方式：**

**4.其他您认为有价值的信息：**
另外，不是很理解为什么要手动计算bodyHeight，初衷是什么

**Comment by olivewind** [comment]
@Zhuzhenghao `dao-panel`的代码将会在下个大版本里被移除，文档里已不再体现。

**Comment by Zhuzhenghao** [comment]
@olivewind 那会有新的组件替代嘛？另外这个现在需要修复吗？
