### ISSUE TITLE
Font bug

### ISSUE THREAD

**Issue by imba-tjd** [DaoCloud/dao-style#688]
https://www.daocloud.io/dce

![image](https://user-images.githubusercontent.com/24759802/54867817-b0b11b80-4dbf-11e9-9eb4-c19e0f6de4e9.png)
![image](https://user-images.githubusercontent.com/24759802/54867828-e0f8ba00-4dbf-11e9-92d7-baf03626616c.png)

我的系统语言是英语。win10 1809 FF Chrome Edge都可复现。

**Comment by qar** [comment]
Thanks for contributing, but this is not a DaoStyle problem.

This issue will be closed. Feel free to reopen it if you have any further questions.

@imba-tjd
